affine_degrees: 0
affine_scale: null
affine_translate: !!python/tuple
- 0.1
- 0.1
architecture_type: cnn2
batch_size: 128
data_dir: ~/Coding/torch_tutorial
flip_p: 0.5
net_params:
  dilation: 1
  dropout_rate: 0.15868832589206244
  kernel_size: 3
  n_intermediate: 1
  out_channels: 64
  padding: same
num_workers: 4
optimizer_params:
  lr: 0.005299937963047945
  weight_decay: 0.0004638254892770786
pin_memory: true
seed: 42
val_fraction: 0.2
